server:
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:
      location: /Users/hanjiyeon/Desktop/문서폴더/project_front/toy/public/upload_image
      maxFileSize: 100MB
      maxRequestSize: 50MB

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/plogging?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      show-sql: true
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${spring.mail.username}
    password: ${spring.mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  header: Authorization
  secret: ${jwt.secret}
  token-validity-in-seconds: 86400



logging:
  level:
    me.j1yeon: DEBUG